window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\hamda\\AppData\\Roaming",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_3832_NPQBEXHANPXWODSJ",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "JESSERHAMDAOUI",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\Windows\\notepad.exe",
  "EFC_10364": "1",
  "GIT_ASKPASS": "c:\\Users\\hamda\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\hamda",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\hamda",
  "INIT_CWD": "C:\\Users\\hamda\\Documents\\GitHub\\carthage-media",
  "INTEL_DEV_REDIST": "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\hamda\\AppData\\Local",
  "LOGONSERVER": "\\\\JESSERHAMDAOUI",
  "MIC_LD_LIBRARY_PATH": "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\mic",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\hamda\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\hamda\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\hamda\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\hamda\\.npm-init.js",
  "npm_config_local_prefix": "C:\\Users\\hamda\\Documents\\GitHub\\carthage-media",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_npm_version": "9.8.0",
  "npm_config_prefix": "C:\\Users\\hamda\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\hamda\\.npmrc",
  "npm_config_user_agent": "npm/9.8.0 node/v20.5.1 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\Users\\hamda\\Documents\\GitHub\\carthage-media\\package.json",
  "npm_package_name": "carthage-media-app",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\hamda\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "12",
  "OneDrive": "C:\\Users\\hamda\\OneDrive",
  "OneDriveConsumer": "C:\\Users\\hamda\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Users\\hamda\\Documents\\GitHub\\carthage-media\\node_modules\\.bin;C:\\Users\\hamda\\Documents\\GitHub\\node_modules\\.bin;C:\\Users\\hamda\\Documents\\node_modules\\.bin;C:\\Users\\hamda\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\hamda\\Documents\\GitHub\\carthage-media\\node_modules\\.bin;C:\\Users\\hamda\\Documents\\GitHub\\node_modules\\.bin;C:\\Users\\hamda\\Documents\\node_modules\\.bin;C:\\Users\\hamda\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\hamda\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\hamda\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\hamda\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\hamda\\AppData\\Roaming\\npm",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "PROCESSOR_LEVEL": "25",
  "PROCESSOR_REVISION": "5000",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\hamda\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\hamda\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.82.2",
  "TMP": "C:\\Users\\hamda\\AppData\\Local\\Temp",
  "USERDOMAIN": "JESSERHAMDAOUI",
  "USERDOMAIN_ROAMINGPROFILE": "JESSERHAMDAOUI",
  "USERNAME": "hamda",
  "USERPROFILE": "C:\\Users\\hamda",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\hamda\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\hamda\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-70df9fb96a-sock",
  "VSCODE_INJECTION": "1",
  "windir": "C:\\Windows"
};